### ISSUE TITLE
Problem with elements

### ISSUE THREAD

**Issue by INDG-SZYMON** [Snapp-Embedded/snapp_cli#20]
Hello, good job, I have one problem, when I run the application on Raspberry I get the following message, the application starts but I can see the appbar and the button, but in the console I have the following information: 
Building Linux application...
cp: -r not specified; omitting directory '/tmp/testrpi/snapp_embedded/flutter_assets/fonts'
cp: -r not specified; omitting directory '/tmp/testrpi/snapp_embedded/flutter_assets/packages'
cp: -r not specified; omitting directory '/tmp/testrpi/snapp_embedded/flutter_assets/shaders'
cp: -r not specified; omitting directory '/tmp/testrpi/snapp_embedded/flutter_assets/fonts'
cp: -r not specified; omitting directory '/tmp/testrpi/snapp_embedded/flutter_assets/packages'
cp: -r not specified; omitting directory '/tmp/testrpi/snapp_embedded/flutter_assets/shaders'

I run flutter run -d pi-4b directly from my windows device in the powershell terminal in the vs code app

**Comment by payam-zahedi** [comment]
Hello @INDG-SZYMON 

I'm sorry I didn't get your point here?

When you run the app, is it runining successfully? 

Or there is an issue with running the app?

or you have problem with these cp errors?

**Comment by payam-zahedi** [comment]
> cp: -r not specified; omitting directory '/tmp/testrpi/snapp_embedded/flutter_assets/fonts'
> cp: -r not specified; omitting directory '/tmp/testrpi/snapp_embedded/flutter_assets/packages'
> cp: -r not specified; omitting directory '/tmp/testrpi/snapp_embedded/flutter_assets/shaders'
> cp: -r not specified; omitting directory '/tmp/testrpi/snapp_embedded/flutter_assets/fonts'
> cp: -r not specified; omitting directory '/tmp/testrpi/snapp_embedded/flutter_assets/packages'
> cp: -r not specified; omitting directory '/tmp/testrpi/snapp_embedded/flutter_assets/shaders'

These lines are not error, This is related to the cp command that we use to copy some files in linux.

**Comment by INDG-SZYMON** [comment]
I'm sorry for the confusion, after a long analysis I found out what the problem was and realized that everything was working properly, we can close the report.

**Comment by almog228** [comment]
> I'm sorry for the confusion, after a long analysis I found out what the problem was and realized that everything was working properly, we can close the report.

What is the problem ? I have same problem
