### ISSUE TITLE
Cannot run the app to Pi 4B

### ISSUE THREAD

**Issue by EnziinSystem** [Snapp-Embedded/snapp_cli#22]
I can list devices

```
snapp_cli devices list

✓  Searching for custom devices completed!

List of custom devices in "C:\Users\enzii\AppData\Roaming\.flutter_custom_devices.json":
  id: pi-5, label: Raspberry Pi 5, enabled: true
  id: pi-4b, label: Raspberry Pi 4 Model B, enabled: true
```

However, it cannot run an application to Pi  4 on debug mode

```
 flutter run -d pi-4b
Launching lib\main.dart on Raspberry Pi 4 Model B in debug mode...
Error: No pubspec.yaml file found.
This command should be run from the root of your Flutter project.
cp: target '/tmp/flutter_application_1/build/flutter_assets' is not a directory
cp: target '/tmp/flutter_application_1/build/linux/arm64/debug/bundle/data/flutter_assets' is not a directory
cp: cannot create regular file '/tmp/flutter_application_1/build/linux/arm64/debug/bundle/data': No such file or directory
bash: line 1: /tmp/flutter_application_1/build/linux/arm64/debug/bundle/flutter_application_1: No such file or directory
```

**Comment by payam-zahedi** [comment]
@EnziinSystem Thanks for opening this issue


I can see this line in the error text 
`Error: No pubspec.yaml file found.`

Is the pubspec.yaml file missing from the root of your project?

**Comment by EnziinSystem** [comment]
> pubspec.yaml

I use Windows for development and deploy to a Pi-4 or Pi-5.
So my project on Windows works on Windows itself and Android, iOS and of course, it has a pubspec.yaml file in the root directory.
This error only appears on Pi-4B and not on other platforms.
It seems to be related to the process of copying files from Windows to Pi-4

**Comment by payam-zahedi** [comment]
Yes you are right that's the problem 

Can you tell me which version of the snapp_cli do you use?

**Comment by payam-zahedi** [comment]
Also, Can you check that you can use passwordless ssh connection?


I mean, you should be able to connect to your raspberry with this simple command without entering the password

`ssh username@ipAddress` 

example 

`ssh pi@192.168.1.10`

**Comment by EnziinSystem** [comment]
> Also, Can you check that you can use passwordless ssh connection?
> 
> I mean, you should be able to connect to your raspberry with this simple command without entering the password
> 
> `ssh username@ipAddress`
> 
> example
> 
> `ssh pi@192.168.1.10`

I still connect SSH via authorized_keys without a password.

```
snapp_cli -v       
Verbose mode enabled

Snapp_cli Current version: 0.5.0
Snapp_cli Latest version: 0.5.0
Snapp_cli needs update: false
```

**Comment by payam-zahedi** [comment]
This is very strange.

If it's possible for you, I would suggest to set time and try to debug it together. 
It's also important for us to find the bugs in snapp cli.

**Comment by EnziinSystem** [comment]
> This is very strange.
> 
> If it's possible for you, I would suggest to set time and try to debug it together. It's also important for us to find the bugs in snapp cli.

I agree with your suggestion, you can even use Teamviewer to access my computer directly.
This is a meaningful project in the embedded field.
I will arrange a time next week.

**Comment by payam-zahedi** [comment]
> Hi any news related to this issue?
> 
> after execute flutter clean and flutter pub get the application start running on rpi 4b.
> 
> Unfortunately I have the following errors.
> 
> Building Linux application... cp: -r not specified; omitting directory '/tmp/counter_app/snapp_embedded/flutter_assets/fonts' cp: -r not specified; omitting directory '/tmp/counter_app/snapp_embedded/flutter_assets/packages' cp: -r not specified; omitting directory '/tmp/counter_app/snapp_embedded/flutter_assets/shaders' cp: -r not specified; omitting directory '/tmp/counter_app/snapp_embedded/flutter_assets/fonts' cp: -r not specified; omitting directory '/tmp/counter_app/snapp_embedded/flutter_assets/packages' cp: -r not specified; omitting directory '/tmp/counter_app/snapp_embedded/flutter_assets/shaders' [ERROR:flutter/shell/common/shell.cc(117)] Dart Error: Can't load Kernel binary: Invalid SDK hash. [ERROR:flutter/runtime/dart_isolate.cc(144)] Could not prepare isolate. [ERROR:flutter/runtime/runtime_controller.cc(462)] Could not create root isolate. [ERROR:flutter/shell/common/shell.cc(669)] Could not launch engine with configuration.
> 
> kind regards

I think you issue is related to your flutter SDK version 

Make sure that you have the same version of the flutter both on your Host and your remote.

**Comment by RootKid87** [comment]
Thanks for quick reply. I will check it 👍🏻

**Comment by EnziinSystem** [comment]
I checked flutter version on both Pi-5 and PC

On Pi-5

```
flutter doctor -v
[✓] Flutter (Channel stable, 3.19.6, on Debian GNU/Linux 12 (bookworm) 6.6.20+rpt-rpi-2712, locale en_GB.UTF-8)
    • Flutter version 3.19.6 on channel stable at /home/developer/sdk/flutter
    • Upstream repository https://github.com/flutter/flutter
    • Framework revision 54e66469a9 (6 days ago), 2024-04-17 13:08:03 -0700
    • Engine revision c4cd48e186
    • Dart version 3.3.4
    • DevTools version 2.31.1
```

On PC

```
flutter --version       
Flutter 3.19.6 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 54e66469a9 (6 days ago) • 2024-04-17 13:08:03 -0700
Engine • revision c4cd48e186
Tools • Dart 3.3.4 • DevTools 2.31.1
```

Run an app demo from PC deploy to Pi-5

```
flutter run -d pi-5
Launching lib\main.dart on Raspberry Pi 5 in debug mode...
Error: No pubspec.yaml file found.
This command should be run from the root of your Flutter project.
cp: target '/tmp/basic/build/flutter_assets': No such file or directory
cp: target '/tmp/basic/build/linux/arm64/debug/bundle/data/flutter_assets': No such file or directory
cp: cannot create regular file '/tmp/basic/build/linux/arm64/debug/bundle/data': No such file or directory
bash: line 1: /tmp/basic/build/linux/arm64/debug/bundle/basic: No such file or directory
```

The problem is unsolved.

**Comment by RootKid87** [comment]
I check the flutter versions on host and pi. On pi it was 3.19.6 and on host 3.19.4. After update to same version no more issues. 👍🏻

**Comment by EnziinSystem** [comment]
Steps that create this problem:

Step 1: Create a new project by VS Code

Step 2: Add window_manage plugin to pubspec.yaml

```
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.6
  window_manager: ^0.3.8
```

VS Code automation run flutter pub get plugins

Step 3: Run deploy to Pi-5

```
flutter run -d pi-5
Launching lib\main.dart on Raspberry Pi 5 in debug mode...
Error: No pubspec.yaml file found.
This command should be run from the root of your Flutter project.
cp: -r not specified; omitting directory '/tmp/smarthome/snapp_embedded/flutter_assets/fonts'
cp: -r not specified; omitting directory '/tmp/smarthome/snapp_embedded/flutter_assets/packages'
cp: -r not specified; omitting directory '/tmp/smarthome/snapp_embedded/flutter_assets/shaders'
cp: target '/tmp/smarthome/build/linux/arm64/debug/bundle/data/flutter_assets': No such file or directory
cp: cannot create regular file '/tmp/smarthome/build/linux/arm64/debug/bundle/data': No such file or directory
bash: line 1: /tmp/smarthome/build/linux/arm64/debug/bundle/smarthome: No such file or directory
```

The reason is the window_manager plugin, but I can't find out specifically.

**Comment by payam-zahedi** [comment]
@EnziinSystem 

I could try to test this scenario with macOS for now.

Snapp cli is working perfectly even if you have added some plugins 


Example:
```dart 
import 'package:flutter/material.dart';
import 'package:window_manager/window_manager.dart';

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();
  // Must add this line.
  await windowManager.ensureInitialized();

  WindowOptions windowOptions = const WindowOptions(
    size: Size(800, 600),
    center: true,
    backgroundColor: Colors.transparent,
    skipTaskbar: false,
    titleBarStyle: TitleBarStyle.hidden,
  );

  windowManager.waitUntilReadyToShow(windowOptions, () async {
    await windowManager.show();
    await windowManager.focus();
  });

  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(seedColor: Colors.deepPurple),
        useMaterial3: true,
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key, required this.title});

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;

  void _incrementCounter() {
    setState(() {
      _counter++;
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        backgroundColor: Theme.of(context).colorScheme.inversePrimary,
        title: Text(widget.title),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            const Text(
              'You have pushed the button this many times:',
            ),
            Text(
              '$_counter',
              style: Theme.of(context).textTheme.headlineMedium,
            ),
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _incrementCounter,
        tooltip: 'Increment',
        child: const Icon(Icons.add),
      ), // This trailing comma makes auto-formatting nicer for build methods.
    );
  }
}

```

**Comment by payam-zahedi** [comment]
@EnziinSystem  


I will also try to reproduce this in windows and linux. 

But probably your problem is related to file/folder access permission.

Can you try to reproduce this with root user?

**Comment by payam-zahedi** [comment]
I will close this issue for now 

Feel free to reopen it if you had the same problem
